name = "Dadiyorto Wendi"
rol = "Climate & Environmental Scientist"
email = "dadiyorto@outlook.com"
location = "Berlin, Germany"
avatar = "./config/assets/avatars/Dadiyorto_Wendi_profile.png"
username = "dadiyorto.wendi" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d160071.78567056425!2d13.36025549536491!3d52.480591611917795!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sde!2sde!4v1719328213796!5m2!1sde!2sde"
presentation = """
I am a climate/ environmental scientist, trained with a PhD in Hydrology and career backgrounds in the topics of climate and water/ flood risk modelling, geospatial data science, solar PV energy, sustainability, and climate resilience entrepreneurship.
"""
